"""create products table

Revision ID: 7fa4917a4b3e
Revises:
Create Date: 2026-09-23 09:26:38.898403

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7fa4917a4b3e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
